### ISSUE TITLE
Mouse aiming

### ISSUE THREAD

**Issue by michaellmonaghan** [pdsimari/CubeQuest#11]

**Comment by michaellmonaghan** [comment]
Do you want to take this one Ciaran?

**Comment by michaellmonaghan** [comment]
There is some code in the init section that you can reference to see how the mouse is grabbed.

**Comment by NeminiCedamus** [comment]
Currently working on this. With the code I have now, I have the player rotating and the camera being locked behind to simulate aiming. The player rotates based upon where the mouse is. Because of this, I'm having to fix bugs that are causing the movement to be messed up. IE the player is moving forward but due to the camera and person rotating, moving forward turns into moving backwards. The shooting is also being affected because of how the movement is being changed. Should have completed code of these by tonight.

-Ciaran

**Comment by NeminiCedamus** [comment]
So I have finished the movement of the character. The character moves forward based on the mouse and holding W key. (I changed to WASD cause lets be honest, who uses arrow keys...) This took me longer to fix properly than I thought so now I am working again on the Camera because that had to be fixed, I have it so it follows the player but not so much that it rotates with the player. I'll try and finish this tonight if I can but I'm jsut giving updates.
